/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Audit */
        get: operations["api_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Audit */
        post: operations["audit_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditInput */
        AuditInput: {
            /** Url */
            url: string;
            seo: components["schemas"]["SEOData"];
            performance: components["schemas"]["PerformanceData"];
            technical: components["schemas"]["TechnicalData"];
        };
        /** AuditReport */
        AuditReport: {
            /** Url */
            url: string;
            /** Company Name */
            company_name: string;
            /** Overall Score */
            overall_score: number;
            /** Executive Summary */
            executive_summary: string;
            seo: components["schemas"]["CategoryScore"];
            performance: components["schemas"]["CategoryScore"];
            technical: components["schemas"]["CategoryScore"];
            content: components["schemas"]["CategoryScore"];
            /** Quick Wins */
            quick_wins: string[];
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            raw_data?: components["schemas"]["AuditInput"] | null;
        };
        /** Body_audit_audit_post */
        Body_audit_audit_post: {
            /** Url */
            url: string;
        };
        /** CategoryScore */
        CategoryScore: {
            /** Score */
            score: number;
            /** Grade */
            grade: string;
            /** Summary */
            summary: string;
            /** Findings */
            findings?: string[];
        };
        /** CoreWebVitals */
        CoreWebVitals: {
            /** Lcp */
            lcp?: number | null;
            /** Cls */
            cls?: number | null;
            /** Fid */
            fid?: number | null;
            /** Fcp */
            fcp?: number | null;
            /** Ttfb */
            ttfb?: number | null;
            /** Speed Index */
            speed_index?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PerformanceData */
        PerformanceData: {
            /** Mobile Score */
            mobile_score?: number | null;
            /** Desktop Score */
            desktop_score?: number | null;
            mobile_vitals?: components["schemas"]["CoreWebVitals"];
            /** Opportunities */
            opportunities?: string[];
            /** Diagnostics */
            diagnostics?: string[];
        };
        /** Recommendation */
        Recommendation: {
            /** Title */
            title: string;
            /** Impact */
            impact: string;
            /** Effort */
            effort: string;
            /** Detail */
            detail: string;
        };
        /** SEOData */
        SEOData: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Meta Description
             * @default
             */
            meta_description: string;
            /** H1 Tags */
            h1_tags?: string[];
            /** H2 Tags */
            h2_tags?: string[];
            /**
             * Canonical Url
             * @default
             */
            canonical_url: string;
            /**
             * Og Title
             * @default
             */
            og_title: string;
            /**
             * Og Description
             * @default
             */
            og_description: string;
            /**
             * Has Schema Markup
             * @default false
             */
            has_schema_markup: boolean;
            /**
             * Images Missing Alt
             * @default 0
             */
            images_missing_alt: number;
            /**
             * Total Images
             * @default 0
             */
            total_images: number;
            /**
             * Internal Links
             * @default 0
             */
            internal_links: number;
            /**
             * External Links
             * @default 0
             */
            external_links: number;
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
            /**
             * Has Cta
             * @default false
             */
            has_cta: boolean;
            /**
             * Has Contact Info
             * @default false
             */
            has_contact_info: boolean;
        };
        /** TechnicalData */
        TechnicalData: {
            /**
             * Status Code
             * @default 200
             */
            status_code: number;
            /**
             * Is Https
             * @default false
             */
            is_https: boolean;
            /**
             * Final Url
             * @default
             */
            final_url: string;
            /**
             * Redirect Count
             * @default 0
             */
            redirect_count: number;
            /**
             * Response Time Ms
             * @default 0
             */
            response_time_ms: number;
            /**
             * Has Robots Txt
             * @default false
             */
            has_robots_txt: boolean;
            /**
             * Has Sitemap
             * @default false
             */
            has_sitemap: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_audit_api_audit_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_audit_audit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
